name = "uskulpt-backend-worker"
main = "worker.js"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"

[vars]
DB_HOST = "uskulpt-db.mysql.database.azure.com"
DB_USER = "admin_at_uskulpt"
DB_PASSWORD = "uskulpt@2030"
DB_NAME = "uskulpt_db"
DB_PORT = "3306"
GOOGLE_CLIENT_ID = "323661162212-8vvl3a3pgkofhhs3cbvpkuulno20k4kd.apps.googleusercontent.com"
JWT_SECRET = "super_secret_jwt_key_uskulpt_2026"
